"use client";
import { FormEvent, useState } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { PublicKey, Transaction } from "@solana/web3.js";
import { ADMIN, initializeConfig, initializePosition, initializeReserve, pauseReserve, positionPda, reservePda, userInstruction } from "@/lib/program";

const markets = [{symbol:"SOL",label:"Solana",apy:"3.84%",ltv:"75%"},{symbol:"USDC",label:"USD Coin",apy:"4.20%",ltv:"80%"},{symbol:"USDT",label:"Tether",apy:"3.96%",ltv:"78%"},{symbol:"xStocks",label:"Tokenized equities",apy:"—",ltv:"Admin"}];
export default function Home() {
  const { connection } = useConnection(); const wallet = useWallet();
  const [form,setForm]=useState({mint:"",vault:"",oracle:"",amount:"",action:"4"}); const [reserve,setReserve]=useState(""); const [feed,setFeed]=useState(""); const [decimals,setDecimals]=useState("6");
  const [status,setStatus]=useState("连接 devnet 钱包后开始"); const isAdmin=wallet.publicKey?.equals(ADMIN) ?? false;
  async function send(ix: ReturnType<typeof initializePosition>) { if(!wallet.publicKey||!wallet.sendTransaction) throw new Error("请先连接钱包"); setStatus("等待钱包确认…"); const sig=await wallet.sendTransaction(new Transaction().add(ix),connection); setStatus("链上确认中…"); await connection.confirmTransaction(sig,"confirmed"); setStatus(`成功 · ${sig.slice(0,12)}…`); }
  async function submit(e:FormEvent){e.preventDefault();try{if(!wallet.publicKey)throw new Error("请先连接钱包");const mint=new PublicKey(form.mint);await send(userInstruction(Number(form.action) as 4|5|6|7,BigInt(form.amount),{user:wallet.publicKey,reserve:reservePda(mint),position:positionPda(wallet.publicKey),userToken:new PublicKey(reserve),mint,vault:new PublicKey(form.vault),oracle:new PublicKey(form.oracle)}));}catch(e){setStatus(e instanceof Error?e.message:"交易失败");}}
  return <main><header><a className="brand" href="#">AEGIS<span>MARKETS</span></a><nav><a href="#markets">市场</a><a href="#position">仓位</a>{isAdmin&&<a href="#admin">管理</a>}</nav><WalletMultiButton /></header>
    <section className="hero"><div><p className="eyebrow">SOLANA DEVNET · PYTH ORACLE</p><h1>流动性，<br/><em>由你掌控。</em></h1><p className="lede">一个受 Aave V3 启发的多资产借贷实验场。支持常见 SPL Token，并为 xStocks 市场预留可配置风控。</p><div className="notice">实验性软件 · 未经审计 · 禁止用于真实资金</div></div><div className="metric"><span>总市场规模</span><strong>$0.00</strong><small>等待管理员初始化 devnet 市场</small></div></section>
    <section id="markets"><div className="section-title"><div><p className="eyebrow">MARKETS</p><h2>可配置资产市场</h2></div><span className="live">DEVNET</span></div><div className="table"><div className="row head"><span>资产</span><span>供应 APY</span><span>最高 LTV</span></div>{markets.map(m=><div className="row" key={m.symbol}><span><b>{m.symbol}</b><small>{m.label}</small></span><span>{m.apy}</span><span>{m.ltv}</span></div>)}</div></section>
    <section id="position" className="workspace"><div><p className="eyebrow">YOUR POSITION</p><h2>仓位操作</h2><p className="muted">首次使用先创建仓位。金额必须填写 token 最小单位。</p><button className="secondary" onClick={()=>wallet.publicKey&&send(initializePosition(wallet.publicKey))}>创建仓位 PDA</button></div><form onSubmit={submit}><label>操作<select value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value="4">供应</option><option value="5">取回</option><option value="6">借入</option><option value="7">还款</option></select></label><label>Mint<input required value={form.mint} onChange={e=>setForm({...form,mint:e.target.value})}/></label><label>用户 Token Account<input required value={reserve} onChange={e=>setReserve(e.target.value)}/></label><label>Vault Token Account<input required value={form.vault} onChange={e=>setForm({...form,vault:e.target.value})}/></label><label>Pyth PriceUpdateV2 Account<input required value={form.oracle} onChange={e=>setForm({...form,oracle:e.target.value})}/></label><label>金额（最小单位）<input required inputMode="numeric" pattern="[0-9]+" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><button type="submit">提交交易</button><output aria-live="polite">{status}</output></form></section>
    {isAdmin&&<section id="admin" className="admin"><p className="eyebrow">ADMIN CONSOLE</p><h2>市场配置</h2><button onClick={()=>send(initializeConfig(ADMIN))}>初始化协议配置</button><label>市场 Mint<input value={form.mint} onChange={e=>setForm({...form,mint:e.target.value})}/></label><label>Pyth Feed ID（hex）<input value={feed} onChange={e=>setFeed(e.target.value)}/></label><label>Decimals<input inputMode="numeric" value={decimals} onChange={e=>setDecimals(e.target.value)}/></label><button onClick={()=>send(initializeReserve(ADMIN,new PublicKey(form.mint),feed,Number(decimals)))}>按保守默认值创建市场</button><label>Reserve PDA<input value={reserve} onChange={e=>setReserve(e.target.value)}/></label><div><button onClick={()=>send(pauseReserve(ADMIN,new PublicKey(reserve),true))}>暂停市场</button><button className="secondary" onClick={()=>send(pauseReserve(ADMIN,new PublicKey(reserve),false))}>恢复市场</button></div></section>}
    <footer><span>Aegis Markets / devnet</span><a href="https://docs.pyth.network/price-feeds" target="_blank" rel="noreferrer">Oracle: Pyth ↗</a></footer></main>;
}
